// List of buildings and their loot types

// By default this list contains buildings from ARMA, ARMA 2 + OA, ARMA 3
// Any classnames that do not exist in-game (i.e. mods that aren't loaded) are simply ignored
// 0 = default/undefined (will spawn in buildings that are not specified below)
// 1 = civil
// 2 = industrial
// 3 = military
// 4 = medical
// 5 = supermarket

scclootListBuildings = [
	
	// ARMA 2 BUILDINGS
	["Land_A_GeneralStore_01",5],
	["Land_A_GeneralStore_01a",5],
	
	// ARMA 3 BUILDINGS
	// ALTIS/STRATIS
	["Land_GH_Gazebo_F", 1],
	["Land_GH_House_2_F", 1],
	["Land_GH_House_1_F", 1],
	["Land_d_House_Small_01_V1_F", 1],
	["Land_u_House_Small_01_V1_F", 1],
	["Land_Metal_Shed_F", 1],
	["Land_i_Garage_V2_F", 1],
	["Land_i_Garage_V1_F", 1],
	["Land_u_House_Small_02_V1_F", 1],
	["Land_d_House_Small_02_V1_F", 1],
	["Land_i_House_Small_02_V3_F", 1],
	["Land_i_House_Small_02_V1_F", 1],
	["Land_i_House_Small_02_V2_F", 1],
	["Land_Chapel_V2_F", 1],
	["Land_Chapel_Small_V1_F", 1],
	["Land_Chapel_Small_V2_F", 1],
	["Land_Chapel_V1_F", 1],
	["Land_d_Addon_02_V1_F", 1],
	["Land_u_Addon_02_V1_F", 1],
	["Land_i_Addon_02_V1_F", 1],
	["Land_i_House_Small_01_V2_F", 1],
	["Land_i_House_Small_01_V1_F", 1],
	["Land_i_House_Small_01_V3_F", 1],
	["Land_i_Addon_03_V1_F", 1],
	["Land_i_Addon_03mid_V1_F", 1],
	["Land_i_Addon_04_V1_F", 1],
	["Land_u_Addon_01_V1_F", 1],
	["Land_Slum_House02_F", 1],
	["Land_Slum_House03_F", 1],
	["Land_LightHouse_F", 1],
	["Land_Kiosk_blueking_F", 1],
	["Land_Kiosk_redburger_F", 1],
	["Land_Kiosk_gyros_F", 1],
	["Land_Kiosk_papers_F", 1],
	["Land_BeachBooth_01_F", 1],
	["Land_LifeguardTower_01_F", 1],
	["Land_TouristShelter_01_F", 1],
	["Land_Amphitheater_F", 1],
	["Land_i_Windmill01_F", 1],
	["Land_i_Stone_HouseBig_V2_F", 1],
	["Land_i_Stone_HouseBig_V1_F", 1],
	["Land_d_Stone_HouseBig_V1_F", 1],
	["Land_i_Stone_HouseBig_V3_F", 1],
	["Land_cargo_house_slum_F", 1],
	["Land_Slum_House01_F", 1],
	["Land_i_Stone_HouseSmall_V3_F", 1],
	["Land_d_Stone_HouseSmall_V1_F", 1],
	["Land_i_Stone_HouseSmall_V1_F", 1],
	["Land_Castle_01_tower_F", 1],
	["Land_i_Stone_HouseSmall_V2_F", 1],
	["Land_i_Stone_Shed_V3_F", 1],
	["Land_i_Stone_Shed_V1_F", 1],
	["Land_d_Stone_Shed_V1_F", 1],
	["Land_i_Stone_Shed_V2_F", 1],
	["Land_u_House_Big_01_V1_F", 1],
	["Land_i_House_Big_02_V1_F", 1],
	["Land_i_House_Small_03_V1_F", 1],
	["Land_u_House_Big_02_V1_F", 1],
	["Land_d_House_Big_02_V1_F", 1],
	["Land_i_House_Big_02_V3_F", 1],
	["Land_i_House_Big_02_V2_F", 1],
	["Land_Offices_01_V1_F", 1],
	["Land_i_House_Big_01_V2_F", 1],
	["Land_i_House_Big_01_V1_F", 1],
	["Land_i_House_Big_01_V3_F", 1],
	["Land_d_House_Big_01_V1_F", 1],
	["Land_u_Shop_02_V1_F", 1],
	["Land_d_Shop_02_V1_F", 1],
	["Land_i_Shop_02_V3_F", 1],
	["Land_i_Shop_02_V1_F", 1],
	["Land_i_Shop_02_V2_F", 1],
	["Land_i_Shop_01_V2_F", 1],
	["Land_i_Shop_01_V1_F", 1],
	["Land_i_Shop_01_V3_F", 1],
	["Land_d_Shop_01_V1_F", 1],
	["Land_u_Shop_01_V1_F", 1],
	
	["Land_dp_mainFactory_F", 2],
	["Land_dp_smallFactory_F", 2],
	["Land_FuelStation_Build_F", 2],
	["Land_FuelStation_Shed_F", 2],
	["Land_CarService_F", 2],
	["Land_Lighthouse_small_F", 2],
	["Land_dp_smallTank_F", 2],
	["Land_Factory_Main_F", 2],
	["Land_dp_bigTank_F", 2],
	["Land_i_Shed_Ind_F", 2],
	["Land_u_Shed_Ind_F", 2],
	["Land_WIP_F", 2],
	["Land_Unfinished_Building_02_F", 2],
	["Land_Unfinished_Building_01_F", 2],
	["Land_Shed_Big_F", 2],
	["Land_fs_roof_F", 2],
	["Land_Crane_F", 2],
	["Land_Shed_Small_F", 2],
	
	["Land_Dome_Big_F", 3],
	["Land_Dome_Small_WIP_F", 3],
	["Land_Dome_Small_WIP2_F", 3],
	["Land_u_Barracks_V2_F", 3],
	["Land_i_Barracks_V1_F", 3],
	["Land_i_Barracks_V2_F", 3],
	["Land_BagBunker_Large_F", 3],
	["Land_BagBunker_Small_F", 3],
	["Land_DeconTent_01_CSAT_brownhex_F", 3],
	["Land_DeconTent_01_AAF_F", 3],
	["Land_DeconTent_01_NATO_F", 3],
	["Land_TentHangar_V1_F", 3],
	["Land_Airport_Tower_F", 3],
	["Land_Radar_F", 3],
	["Land_Hangar_F", 3],
	["Land_Cargo_House_V3_F", 3],
	["Land_Cargo_House_V1_F", 3],
	["Land_Medevac_house_V1_F", 3],
	["Land_Cargo_House_V2_F", 3],
	["Land_BagBunker_Tower_F", 3],
	["Land_Cargo_Tower_V2_F", 3],
	["Land_Cargo_Tower_V1_No1_F", 3],
	["Land_Cargo_Tower_V1_No2_F", 3],
	["Land_Cargo_Tower_V1_No3_F", 3],
	["Land_Cargo_Tower_V1_No4_F", 3],
	["Land_Cargo_Tower_V1_No5_F", 3],
	["Land_Cargo_Tower_V1_No6_F", 3],
	["Land_Cargo_Tower_V1_No7_F", 3],
	["Land_Cargo_Tower_V1_F", 3],
	["Land_Cargo_Tower_V3_F", 3],
	["Land_Cargo_HQ_V2_F", 3],
	["Land_Cargo_HQ_V1_F", 3],
	["Land_Cargo_HQ_V3_F", 3],
	["Land_Medevac_HQ_V1_F", 3],
	["Land_Cargo_Patrol_V2_F", 3],
	["Land_Cargo_Patrol_V1_F", 3],
	["Land_Cargo_Patrol_V3_F", 3],
	["Land_MilOffices_V1_F", 3],
	["Land_Research_HQ_F", 3],
	["Land_Research_house_V1_F", 3],
	["Land_MedicalTent_01_aaf_generic_open_F", 3],
	["Land_MedicalTent_01_CSAT_brownhex_generic_open_F", 3],
	["Land_MedicalTent_01_NATO_generic_open_F", 3],
	["Land_MedicalTent_01_aaf_generic_inner_F", 3],
	["Land_MedicalTent_01_CSAT_brownhex_generic_inner_F", 3],
	["Land_MedicalTent_01_NATO_generic_inner_F", 3],
	["Land_MedicalTent_01_aaf_generic_outer_F", 3],
	["Land_MedicalTent_01_CSAT_brownhex_generic_outer_F", 3],
	["Land_MedicalTent_01_NATO_generic_outer_F", 3],
	
	["Land_MedicalTent_01_white_IDAP_outer_F", 4],
	["Land_MedicalTent_01_white_IDAP_open_F", 4],
	["Land_MedicalTent_01_white_generic_outer_F", 4],
	["Land_MedicalTent_01_white_generic_open_F", 4],
	["Land_MedicalTent_01_white_generic_inner_F", 4],
	["Land_DeconTent_01_IDAP_F", 4],
	["Land_DeconTent_01_yellow_F", 4],
	["Land_DeconTent_01_white_F", 4],
	
	// TANOA
	["Land_House_Big_05_F", 1],
	["Land_Shed_04_F", 1],
	["Land_Shed_01_F", 1],
	["Land_Shed_07_F", 1],
	["Land_Shop_Town_02_F", 1],
	["Land_Shop_Town_01_F", 1],
	["Land_Shop_Town_05_F", 1],
	["Land_Shop_Town_03_F", 1],
	["Land_GarageShelter_01_F", 1],
	["Land_Slum_01_F", 1],
	["Land_Slum_02_F", 1],
	["Land_House_Small_02_F", 1],
	["Land_House_Big_02_F", 1],
	["Land_House_Small_03_F", 1],
	["Land_House_Small_06_F", 1],
	["Land_Shed_05_F", 1],
	["Land_Shed_02_F", 1],
	["Land_House_Small_01_F", 1],
	["Land_Slum_03_F", 1],
	["Land_Hotel_01_F", 1],
	["Land_Hotel_02_F", 1],
	["Land_Shop_City_03_F", 1],
	["Land_Cathedral_01_F", 1],
	["Land_House_Native_02_F", 1],
	["Land_Temple_Native_01_F", 1],
	["Land_House_Native_01_F", 1],
	["Land_Shop_Town_04_F", 1],
	["Land_Shop_City_06_F", 1],
	["Land_Shop_City_05_F", 1],
	["Land_Shop_City_07_F", 1],
	["Land_Addon_04_F", 1],
	["Land_House_Big_03_F", 1],
	["Land_Airport_01_terminal_F", 1],
	["Land_Shop_City_01_F", 1],
	["Land_Shop_City_02_F", 1],
	["Land_School_01_F", 1],
	["Land_House_Small_04_F", 1],
	["Land_House_Small_05_F", 1],
	["Land_Airport_02_terminal_F", 1],
	["Land_House_Big_04_F", 1],
	["Land_MultistoryBuilding_03_F", 1],
	["Land_Shop_City_04_F", 1],
	["Land_MultistoryBuilding_04_F", 1],
	["Land_MultistoryBuilding_01_F", 1],
	["Land_House_Big_01_F", 1],
	["Land_Mausoleum_01_F", 1],
	
	["Land_StorageTank_01_small_F", 2],
	["Land_Warehouse_02_F", 2],
	["Land_Warehouse_01_F", 2],
	["Land_StorageTank_01_large_F", 2],
	["Land_SM_01_reservoirTower_F", 2],
	["Land_SM_01_shelter_wide_F", 2],
	["Land_SM_01_shelter_narrow_F", 2],
	["Land_WaterTower_01_F", 2],
	["Land_FuelStation_02_workshop_F", 2],
	["Land_FuelStation_01_workshop_F", 2],
	["Land_FuelStation_01_shop_F", 2],
	["Land_Warehouse_03_F", 2],
	["Land_SCF_01_washer_F", 2],
	["Land_SCF_01_storageBin_big_F", 2],
	["Land_SCF_01_storageBin_medium_F", 2],
	["Land_SCF_01_storageBin_small_F", 2],
	["Land_SCF_01_generalBuilding_F", 2],
	["Land_SCF_01_diffuser_F", 2],
	["Land_SCF_01_crystallizer_F", 2],
	["Land_SCF_01_condenser_F", 2],
	["Land_SCF_01_crystallizerTowers_F", 2],
	["Land_SCF_01_chimney_F", 2],
	["Land_SCF_01_clarifier_F", 2],
	["Land_SM_01_shed_unfinished_F", 2],
	["Land_SM_01_shed_F", 2],
	["Land_DPP_01_smallFactory_F", 2],
	["Land_DPP_01_mainFactory_F", 2],
	["Land_SCF_01_boilerBuilding_F", 2],
	["Land_MobileCrane_01_hook_F", 2],
	["Land_MobileCrane_01_F", 2],
	
	["Land_GuardHouse_01_F", 3],
	["Land_MedicalTent_01_CSAT_greenhex_generic_inner_F", 3],
	["Land_MedicalTent_01_NATO_tropic_generic_inner_F", 3],
	["Land_MedicalTent_01_CSAT_greenhex_generic_open_F", 3],
	["Land_MedicalTent_01_NATO_tropic_generic_open_F", 3],
	["Land_MedicalTent_01_CSAT_greenhex_generic_outer_F", 3],
	["Land_MedicalTent_01_NATO_tropic_generic_outer_F", 3],
	["Land_DeconTent_01_CSAT_greenhex_F", 3],
	["Land_DeconTent_01_NATO_tropic_F", 3],
	["Land_Cargo_House_V4_F", 3],
	["Land_Cargo_HQ_V4_F", 3],
	["Land_Cargo_Patrol_V4_F", 3],
	["Land_Cargo_Tower_V4_F", 3],
	["Land_PillboxBunker_01_big_F", 3],
	["Land_PillboxBunker_01_rectangle_F", 3],
	["Land_PillboxBunker_01_hex_F", 3],
	["Land_Barracks_01_dilapidated_F", 3],
	["Land_Barracks_01_grey_F", 3],
	["Land_Barracks_01_camo_F", 3],
	["Land_Airport_01_hangar_F", 3],
	["Land_Airport_02_controlTower_F", 3],
	["Land_Airport_01_controlTower_F", 3],
	["Land_Airport_02_hangar_right_F", 3],
	["Land_Airport_02_hangar_left_F", 3],
	
	["Land_Supermarket_01_F", 5]
	
];

// Blackisted Buildings
// Building classes in this array will never spawn loot
scclootBlacklistBuildings = [
	
	"Land_Bridge_01_PathLod_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_Pier_F",
	"Land_Pier_small_F",
	"Land_MultistoryBuilding_01_F"
	
];